#!/usr/bin/env bash
# deploy.sh — put THIS code on the GPU box, and prove it landed.
#
# WHY THIS EXISTS
#   The pod ran a copy of kevacv/ made once by setup_pod.sh, and bootstrap.sh
#   skipped setup whenever the venv already existed. So the box re-ran frozen
#   code for five days, produced identical output every time, and nothing
#   anywhere said so. Every "fix" in that window was invisible by construction.
#
#   This closes that hole three ways:
#     1. rsync --delete, so a file deleted here disappears there. A plain copy
#        leaves orphans behind, and an orphaned .py that something still
#        imports is the same stale-code bug wearing a different hat.
#     2. __pycache__ is wiped on both sides. A stale .pyc whose source is gone
#        still imports, which is this bug with no visible cause at all.
#     3. The build id is computed on BOTH machines and compared. If they do
#        not match, this exits non-zero and names the files that differ,
#        instead of letting you run and wonder.
#
# USAGE
#   tools/deploy.sh user@host                    # sync + verify
#   tools/deploy.sh user@host /opt/keva          # custom remote path
#   KEY=~/.ssh/id.pem tools/deploy.sh ubuntu@host        # EC2 / .pem key
#   REMOTE_PY=python3.11 tools/deploy.sh user@host
#
# KEY is passed to BOTH ssh and rsync. Passing it to only one is a classic
# half-working deploy: the build-id check authenticates fine while the file
# transfer silently prompts for a password and hangs, or vice versa.
#
# It deliberately does NOT run the pipeline. Deploy and run are separate steps
# so a failed sync can never look like a bad run.

set -Eeuo pipefail

REMOTE="${1:-}"
REMOTE_DIR="${2:-/workspace/keva_vision}"
REMOTE_PY="${REMOTE_PY:-python3}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# `python` does not exist on a stock Ubuntu/WSL; `python3` does not exist on
# some Windows setups. Pick whichever is actually here rather than making the
# caller discover it from a "command not found".
if [[ -z "${LOCAL_PY:-}" ]]; then
  # Test that it RUNS, not merely that it is on PATH. Windows ships a
  # python3.exe stub that exists, resolves, and does nothing but print an
  # advert for the Microsoft Store — command -v is happy and every later step
  # fails with a message about nothing.
  for c in python3 python py; do
    if command -v "$c" >/dev/null 2>&1 && "$c" -c 'print(1)' >/dev/null 2>&1; then
      LOCAL_PY="$c"; break
    fi
  done
fi
if [[ -z "${LOCAL_PY:-}" ]]; then
  echo "!! no python found locally (tried python3, python, py)" >&2; exit 2
fi

if [[ -z "$REMOTE" ]]; then
  echo "usage: tools/deploy.sh user@host [remote_dir]" >&2
  echo "       KEY=~/.ssh/key.pem tools/deploy.sh ubuntu@host" >&2
  exit 2
fi

# Build the ssh command once, so ssh and rsync cannot drift apart.
SSH_CMD="ssh"
if [[ -n "${KEY:-}" ]]; then
  KEY_EXPANDED="${KEY/#\~/$HOME}"
  if [[ ! -f "$KEY_EXPANDED" ]]; then
    echo "!! key not found: $KEY_EXPANDED" >&2
    echo "   (note ~/.ssh/ vs ~/ssh/ — they are different directories)" >&2
    exit 2
  fi
  # A .pem with loose permissions is refused by ssh outright. On a Windows
  # filesystem the mode is often 0777, so say what to do rather than letting
  # ssh fail with its own less obvious message.
  SSH_CMD="ssh -i \"$KEY_EXPANDED\" -o IdentitiesOnly=yes"
fi
SSH_OPTS="${SSH_OPTS:-}"
[[ -n "$SSH_OPTS" ]] && SSH_CMD="$SSH_CMD $SSH_OPTS"

# shellcheck disable=SC2086
sshx() { eval "$SSH_CMD" "\"\$@\""; }

echo "=== local build ==="
"$LOCAL_PY" "$ROOT/kevacv/build_id.py"
LOCAL_ID="$( "$LOCAL_PY" "$ROOT/kevacv/build_id.py" --id )"

echo
echo "=== clearing local caches ==="
# A .pyc whose .py no longer exists still imports. Removing them here means
# the thing we hash is the thing that runs.
find "$ROOT" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

echo "=== syncing to ${REMOTE}:${REMOTE_DIR} ==="
sshx "$REMOTE" "mkdir -p '${REMOTE_DIR}'"
# --delete is the point of this script. Excludes are outputs and inputs, never
# code: models/ and data/ are gigabytes that belong to the box, and output/
# and logs/ are produced THERE and must not be overwritten from here.
rsync -az --delete -e "$SSH_CMD" \
  --exclude '.git/' \
  --exclude '__pycache__/' \
  --exclude '*.pyc' \
  --exclude 'output/' \
  --exclude 'logs/' \
  --exclude 'data/' \
  --exclude 'models/' \
  --exclude '_archive/' \
  --exclude 'label_pkg/' \
  --exclude '*_gt.txt' \
  "$ROOT"/ "${REMOTE}:${REMOTE_DIR}/"
# label_pkg/ and *_gt.txt are HUMAN OUTPUT, not code. --delete removes anything
# on the box that is not here, and on 2026-08-15 that silently destroyed a
# freshly built label package seconds after it was made. The same thing would
# have eaten an afternoon of CVAT labelling — the one artefact in this project
# that cannot be regenerated by re-running anything.

echo
echo "=== remote build ==="
REMOTE_ID="$( sshx "$REMOTE" "cd '${REMOTE_DIR}' && find . -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null; ${REMOTE_PY} kevacv/build_id.py --id" )"

echo "  local  ${LOCAL_ID}"
echo "  remote ${REMOTE_ID}"
if [[ "$LOCAL_ID" != "$REMOTE_ID" ]]; then
  echo
  echo "!! BUILD MISMATCH — the box is NOT running this code." >&2
  echo "   Files that differ:" >&2
  sshx "$REMOTE" "cd '${REMOTE_DIR}' && ${REMOTE_PY} kevacv/build_id.py --manifest" \
    > /tmp/remote_manifest.json 2>/dev/null || true
  ( cd "$ROOT" && "$LOCAL_PY" - <<'PY' >&2 || true
import json, pathlib, sys
sys.path.insert(0, "kevacv")
import build_id                      # the FILE, not the package
try:
    theirs = json.loads(pathlib.Path("/tmp/remote_manifest.json").read_text())
except Exception:
    print("   (could not read the remote manifest)"); raise SystemExit
d = build_id.diff(theirs, pkg_dir="kevacv")
for k, v in d.items():
    if v:
        print(f"     {k}: {', '.join(v)}")
PY
  )
  exit 1
fi

echo
echo "  MATCH — the box is running exactly this code."
echo
echo "Next, on the box:"
echo "  cd ${REMOTE_DIR}"
echo "  ${REMOTE_PY} tools/run_pipeline.py --drive-folder <id> --chunk '6.30.00pm' \\"
echo "      --zones zones/CAM.112_zone.json --eval-export --dataset-export \\"
echo "      --dry --out output/smoke"
echo
echo "Start with --dry: 20 seconds of footage proves weights, CUDA, zones and"
echo "the writer in about a minute, instead of failing at minute 50."

echo
echo "Note: no --no-render. You want the annotated video, and its HUD will"
echo "show build ${LOCAL_ID} — check that before trusting anything in it."
