"""stamp_build.py — make the notebook say WHICH build is running. Idempotent.

THE PROBLEM THIS SOLVES
    Cell 1 printed two lines on every run:

        NOTEBOOK BUILD: v55 (...) — stale tag? re-import.
        you are running a stale import: File > Import Notebook > re-import.

    The first is a HARDCODED string. It said "v55" while the notebook was at
    v56 phase 11 — eleven phases of fixes later. The second is an
    unconditional print: it claims the import is stale EVERY time, whether it
    is or not.

    So a warning that is always on tells you nothing, and the version tag lies.
    Between them there was no way to answer the only question that matters
    after making a change: "did the thing I just fixed actually run?"

    That is why fixes appeared not to work. Not because they were wrong —
    because there was no way to tell a fresh import from a stale one, and the
    banner said v55 either way.

WHAT THIS DOES
    Derives the banner from the notebook's ACTUAL content: every PHASE marker
    present, plus a short content hash. Re-run it after any patch. If the
    Kaggle output does not show the phases you expect, you are running a stale
    import — and now that statement means something, because it is computed
    rather than asserted.

Run: python stamp_build.py
"""
import hashlib
import json
import re
from pathlib import Path

NB = Path(__file__).resolve().parent.parent / "notebooks" / "pipeline.ipynb"
BEGIN = "# >>> BUILD BANNER (generated by stamp_build.py) >>>"
END = "# <<< BUILD BANNER <<<"

nb = json.loads(NB.read_text(encoding="utf-8"))
body = json.dumps(nb["cells"][1:])
digest = hashlib.sha256(body.encode()).hexdigest()[:10]

markers = sorted(set(re.findall(r"PHASE\d+[A-Z_]*", body)))
phases = sorted({int(re.match(r"PHASE(\d+)", m).group(1)) for m in markers})

banner = f'''{BEGIN}
# Regenerate with: python stamp_build.py   (never hand-edit)
_BUILD_ID = "{digest}"
_BUILD_PHASES = {phases!r}
_BUILD_MARKERS = {markers!r}
print(f"NOTEBOOK BUILD {{_BUILD_ID}} \\u00b7 phases applied: "
      f"{{', '.join(str(p) for p in _BUILD_PHASES) or 'none'}}")
print("  If the phases above are not the ones you just patched in, you are "
      "running a STALE import -> File \\u25b8 Import Notebook \\u25b8 re-import.")
print("  (This list is computed from the notebook's own content. The old "
      "banner was a hardcoded 'v55' string that never changed, beside a "
      "'stale import' warning that printed unconditionally on every run — "
      "which is why a real fix could look like it had done nothing.)")
{END}'''

src = "".join(nb["cells"][0]["source"])

if BEGIN in src:
    # lambda, not the string: re.sub parses backslash escapes in a replacement,
    # and the banner contains · — which raised "bad escape \u" on the
    # second run. A patch script that only works once is not idempotent.
    src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END),
                 lambda _m: banner, src, flags=re.S)
    action = "refreshed"
else:
    old = [l for l in src.splitlines()
           if l.startswith('print("NOTEBOOK BUILD:')
           or l.startswith('print("you are running a stale import')]
    for l in old:
        src = src.replace(l + "\n", "")
    lines = src.splitlines()
    at = 1 if lines and lines[0].lstrip().startswith("#") else 0
    src = "\n".join(lines[:at] + [banner] + lines[at:])
    action = f"installed (removed {len(old)} hardcoded line(s))"

nb["cells"][0]["source"] = src
NB.write_text(json.dumps(nb, indent=1), encoding="utf-8")

print(f"build banner {action}")
print(f"  build id : {digest}")
print(f"  phases   : {phases}")
print(f"  markers  : {len(markers)} -> {markers}")
